# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: CC-BY-4.0

name: Deploy ABC

env:
  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      image: ${{ steps.build.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if package already exists
        run: (make check-if-tag-exists DOCKER_REGISTRY=${DOCKER_REGISTRY} && echo "PUSH=true" >> $GITHUB_ENV) || echo "PUSH=false" >> $GITHUB_ENV
          
      - name: Build and Push
        id: build
        if: ${{ env.PUSH == 'true' }}
        run: |
          make push-server DOCKER_REGISTRY=${DOCKER_REGISTRY}
          image_name=$(make image-name)
          image_digest=$(docker images --no-trunc --quiet ${image_name})
          echo "image=${image_name}" >> "$GITHUB_OUTPUT"
          echo "digest=${image_digest}" >> "$GITHUB_OUTPUT"

  # This step calls the container workflow to generate provenance and push it to
  # the container registry.
  provenance:
    needs: [publish]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
    with:
      image: ${{ needs.publish.outputs.image }}
      digest: ${{ needs.publish.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}